"""Changing column name to status

Revision ID: 008fe3de1c25
Revises: da3a7a41675c
Create Date: 2021-05-15 20:09:16.130377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008fe3de1c25'
down_revision = 'da3a7a41675c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.String(), nullable=True))
    with op.batch_alter_table("project") as batch_op:
        batch_op.drop_column('state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('state', sa.VARCHAR(), nullable=True))
    with op.batch_alter_table("project") as batch_op:
        batch_op.drop_column('status')
   
    # ### end Alembic commands ###
