"""Adding new columns and changing tyoe

Revision ID: 0e23f982e5bf
Revises: b9888e52e087
Create Date: 2021-05-12 18:33:15.155034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e23f982e5bf'
down_revision = 'b9888e52e087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('state', sa.String(), nullable=True))
    op.add_column('project', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'creation_date')
    op.drop_column('project', 'state')
    # ### end Alembic commands ###
