"""2020-07-22- Adding lat and lon columns

Revision ID: 30c32a5e035b
Revises: d9833766ae2c
Create Date: 2021-07-22 22:07:10.357130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30c32a5e035b'
down_revision = 'd9833766ae2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('location', sa.Column('lon', sa.Float(), nullable=True))
    op.alter_column('project', 'status',
               existing_type=postgresql.ENUM('in_progres', 'ended', 'pending', 'initialized', name='project_status'),
               type_=sa.Enum('initialized', 'in_progres', 'ended', 'pending', name='project_status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'status',
               existing_type=sa.Enum('initialized', 'in_progres', 'ended', 'pending', name='project_status'),
               type_=postgresql.ENUM('in_progres', 'ended', 'pending', 'initialized', name='project_status'),
               nullable=False)
    op.create_index('idx_location_point', 'location', ['point'], unique=False)
    op.drop_column('location', 'lon')
    op.drop_column('location', 'lat')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
