"""Adding number to stage table

Revision ID: 3d766fdd32b8
Revises: 616082190e9c
Create Date: 2021-06-28 23:01:12.854984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d766fdd32b8'
down_revision = '616082190e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage', 'number')
    # ### end Alembic commands ###
