"""Updating project location

Revision ID: 5488954fb77e
Revises: 3d766fdd32b8
Create Date: 2021-07-03 18:25:16.806230

"""
from alembic import op
import sqlalchemy as sa
from  geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = '5488954fb77e'
down_revision = '3d766fdd32b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('point', Geometry(
                            geometry_type='POINT',
                            srid=4326,
                            from_text='ST_GeogFromText',
                            name='geography',
                            ),
                        nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('project', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_table('location')
    # ### end Alembic commands ###
