"""Adding stages to project

Revision ID: 616082190e9c
Revises: 60751180e888
Create Date: 2021-06-27 21:10:02.519383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616082190e9c'
down_revision = '60751180e888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('initialized', 'in_progres', 'ended', 'pending', name='stage_status'), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    # ### end Alembic commands ###
