"""Adding assigned status

Revision ID: 923b45c6d38c
Revises: 93180f36a377
Create Date: 2021-06-09 00:18:41.032999

"""
from alembic import op as batch_op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '923b45c6d38c'
down_revision = '93180f36a377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    assigned_status = postgresql.ENUM('pending', 'confirmed', 'rejected', name='assigned_status')
    assigned_status.create(batch_op.get_bind())
    batch_op.add_column('overseer', sa.Column('assigned_status', sa.Enum('pending', 'confirmed', 'rejected', name='assigned_status'), nullable=True))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    batch_op.drop_column('overseer', 'assigned_status')
    assigned_status = postgresql.ENUM('pending', 'confirmed', 'rejected', name='assigned_status')
    assigned_status.drop(batch_op.get_bind())
    # ### end Alembic commands ###
