"""adding overseer table

Revision ID: 93180f36a377
Revises: 26629b5c6513
Create Date: 2021-06-08 21:49:16.695047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93180f36a377'
down_revision = '26629b5c6513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overseer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_overseer_association',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('overseer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['overseer_id'], ['overseer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_overseer_association')
    op.drop_table('overseer')
    # ### end Alembic commands ###
