"""Adding column

Revision ID: ffd6b7a515ce
Revises: 440d4dc6c337
Create Date: 2021-05-09 16:18:25.113598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd6b7a515ce'
down_revision = '440d4dc6c337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('target_amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'target_amount')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
